#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"

[[repos.hooks]]
id = "check-fmt"
name = "check-fmt"
language = "system"
entry = "just check-fmt"
pass_filenames = false

[[repos.hooks]]
id = "check"
name = "check"
language = "system"
entry = "just check"
stages = ["pre-push"]
pass_filenames = false
